name: Gradle CI

on:
  push:
    branches: [ main, gh_action, backend ]
  pull_request:
    branches: [ main, backend ]

defaults:
  run:
    working-directory: ./backend

jobs:
  buildAndRunTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew test
