name: FE CI

on:
  push:
    branches:
      - gh_action
      - main
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
      - with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build, test
        run: |
          cd client
          npm install
          npm run build
          npm test ./test/*
