name: Node.js CI

on:
  push:
    branches: [ main, frontend ]
  pull_request:
    branches: [ main, frontend ]

# defaults:
#   run:
#     working-directory: ./client

jobs:
  simpleTests:
    defaults:
      run:
        working-directory: ./client
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test ./test/*

  selenideTests:
    defaults:
      run:
        working-directory: ./client
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: dir
      - run: ./gradlew test --stacktrace
